apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apis1
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: "kong"
  rules:
    - http:
        paths:
          - path: /api/v1.0/ms1/
            pathType: Prefix
            backend:
              service:
                name: fiap-app-orders-service
                port:
                  number: 8080
